# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField()),
                ('optimal_f', models.FloatField()),
                ('optimal_m', models.FloatField()),
                ('c0', models.FloatField()),
                ('c1', models.FloatField()),
                ('c2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('app_satisfication', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InputConvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vo', models.FloatField()),
                ('vt', models.FloatField()),
                ('ve', models.FloatField()),
                ('vd', models.FloatField()),
                ('td', models.FloatField()),
                ('m', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelersInput',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=50)),
                ('desire_arrival_time', models.TimeField()),
                ('on_time_importance', models.IntegerField()),
                ('late_dissatisfication', models.IntegerField()),
                ('early_dissatisfication', models.IntegerField()),
                ('destination_activity', models.CharField(max_length=50)),
                ('no_late', models.IntegerField()),
                ('no_early', models.IntegerField()),
                ('agree', models.IntegerField()),
                ('late_prob', models.IntegerField()),
                ('early_prob', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelersOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('late_prob', models.FloatField()),
                ('early_prob', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.TravelersInput')),
            ],
        ),
        migrations.AddField(
            model_name='inputconvert',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.TravelersInput'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.TravelersInput'),
        ),
        migrations.AddField(
            model_name='algorithmoutput',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.TravelersInput'),
        ),
    ]
