# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelersinput',
            name='desire_arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='travelersinput',
            name='early_dissatisfication',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='travelersinput',
            name='late_dissatisfication',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='travelersinput',
            name='no_early',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='travelersinput',
            name='no_late',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='travelersinput',
            name='on_time_importance',
            field=models.IntegerField(null=True),
        ),
    ]
