# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20170430_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelersinput',
            name='agree',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='travelersinput',
            name='early_prob',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='travelersinput',
            name='late_prob',
            field=models.IntegerField(null=True),
        ),
    ]
