# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20170430_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTimeDistributation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField()),
                ('sd', models.FloatField()),
                ('pt', models.CharField(max_length=100)),
                ('tmin', models.FloatField()),
                ('tmax', models.FloatField()),
                ('tM', models.FloatField()),
                ('to', models.FloatField()),
                ('landa1', models.FloatField()),
                ('landa2', models.FloatField()),
                ('td', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.TravelersInput')),
            ],
        ),
    ]
