# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_traveltimedistributation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithmoutput',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='inputconvert',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='travelersinput',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='travelersoutput',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='traveltimedistributation',
            old_name='user_id',
            new_name='user',
        ),
    ]
